[package]
name = "connect"
version = "0.1.0"
edition = "2021"

[dependencies]
common.workspace = true

futures.workspace = true
serio.workspace = true
tokio.workspace = true

[[bin]]
name = "alice"
path = "src/alice.rs"

[[bin]]
name = "bob"
path = "src/bob.rs"
